#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE OPENSONDAGE CONFIGURATION
#=================================================
ynh_script_progression "Reconfiguring $app..."

ynh_replace --match="const APP_URL = '$old_domain';" --replace="const APP_URL = '$new_domain';" --file="$install_dir/app/inc/config.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
