#!/bin/bash

set -eu

app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
language=$YNH_APP_ARG_LANGUAGE
is_public=$YNH_APP_ARG_IS_PUBLIC
legal='no'

# Source YunoHost helpers
. /usr/share/yunohost/helpers

# Check if admin exists
sudo yunohost user list --json | grep -q "\"username\": \"$admin\"" \
    || ynh_die "Wrong admin"

ynh_app_setting_set "$app" admin "$admin"
ynh_app_setting_set "$app" language "$language"
ynh_app_setting_set "$app" legal "$legal"
ynh_app_setting_set "$app" is_public "$is_public"
# Deprecated
ynh_app_setting_set "$app" public_site "$is_public"

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path}"

# Copy files to the right place
final_path=/var/www/$app
sudo mkdir -p $final_path
sudo cp -a ../sources/. $final_path
sudo cp ../conf/constants.php.template $final_path/app/inc/constants.php

# Generate MySQL password and create database
dbuser=$app
dbname=$app
dbpass=$(ynh_string_random 12)
ynh_app_setting_set "$app" mysqlpwd "$dbpass"
ynh_mysql_create_db "$dbname" "$dbuser" "$dbpass"

# Load initial SQL into the new database
ynh_mysql_connect_as "$dbuser" "$dbpass" "$dbname" \
    < $final_path/install.mysql.sql

# Change variables in configuration
sudo sed -i "s/yunouser/$dbuser/g" $final_path/app/inc/constants.php
sudo sed -i "s/yunopass/$dbpass/g" $final_path/app/inc/constants.php
sudo sed -i "s/yunobase/$dbname/g" $final_path/app/inc/constants.php
sudo sed -i "s/yunoadmin/$admin/g" $final_path/app/inc/constants.php
sudo sed -i "s/I18NTOCHANGE/$language/g" $final_path/app/inc/constants.php
sudo sed -i "s@yunourl@$domain$path@g" $final_path/app/inc/constants.php
sudo sed -i "s@yunodomain@$domain@g" $final_path/app/inc/constants.php
sudo sed -i "s@yunoabout@$legal@g" $final_path/app/inc/constants.php

# Create log file
touch $final_path/admin/logs_studs.txt
sudo chmod 700 $final_path/admin/logs_studs.txt
# Set permissions
sudo chown -R www-data: $final_path

# Modify PHP-FPM pool configuration and copy it to the pool directory
sed -i "s@NAMETOCHANGE@$app@g" ../conf/php-fpm.conf
finalphpconf=/etc/php5/fpm/pool.d/$app.conf
sudo cp ../conf/php-fpm.conf $finalphpconf
sudo chown root: $finalphpconf
sudo chmod 644 $finalphpconf

finalphpini=/etc/php5/fpm/conf.d/20-$app.ini
sudo cp ../conf/php-fpm.ini $finalphpini
sudo chown root: $finalphpini
sudo chmod 644 $finalphpini

# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm restart

sudo DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" -y --force-yes -qq install php-fpdf
sudo yunohost app addaccess $app -u $admin

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
ynh_app_setting_set "$app" skipped_uris "/"
if [[ $is_public -eq 0 ]];
then
	ynh_app_setting_set "$app" protected_uris "/admin,/index.php,/choix_date.php,/choix_autre.php,/infos_sondage.php,/scripts"
else
	ynh_app_setting_set "$app" protected_uris "/admin/index.php,/admin/logs_studs.txt,/scripts"
fi
sudo yunohost app ssowatconf
