#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
language=$YNH_APP_ARG_LANGUAGE
is_public=$YNH_APP_ARG_IS_PUBLIC

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================

final_path=/var/www/$app
test ! -e "$final_path" || ynh_die "This path already contains a folder"

# Normalize the url path syntax
path_url=$(ynh_normalize_url_path "$path_url")

# Check web path availability
ynh_webpath_available "$domain" "$path_url"
# Register (book) web path
ynh_webpath_register "$app" "$domain" "$path_url"

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set "$app" domain "$domain"
ynh_app_setting_set "$app" path_url "$path_url"
ynh_app_setting_set "$app" admin "$admin"
ynh_app_setting_set "$app" language "$language"
ynh_app_setting_set "$app" is_public "$is_public"

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# INSTALL DEPENDENCIES
#=================================================

ynh_install_app_dependencies php-fpdf

#=================================================
# CREATE A MYSQL DATABASE
#=================================================

# Generate MySQL password and create database
dbuser=$app
db_name=$app
dbpass=$(ynh_string_random 12)
ynh_app_setting_set "$app" mysqlpwd "$dbpass"
ynh_app_setting_set "$app" db_name "$db_name"
ynh_mysql_create_db "$db_name" "$dbuser" "$dbpass"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_app_setting_set "$app" final_path "$final_path"
# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source "$final_path"

#=================================================
# NGINX CONFIGURATION
#=================================================

if [ "$path_url" == "/" ]
then
	# ynh panel is only for non-root installs
	ynh_replace_string "	include conf.d/"  "	#include conf.d/"  "../conf/nginx.conf"
else
	# add rewrite for alias_traversal protection
	ynh_replace_string "^#sub_path_only" "" "../conf/nginx.conf"
fi

# Create a dedicated nginx config
ynh_add_nginx_config

#=================================================
# CREATE DEDICATED USER
#=================================================

# Create a system user
ynh_system_user_create "$app"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================

# Create a dedicated php-fpm config
ynh_add_fpm_config

#=================================================
# SPECIFIC SETUP
#=================================================
# Create config.php
#=================================================

config="$final_path/app/inc/config.php"
admin_mail=$(ynh_user_get_info "$admin" mail)
cp ../conf/config.php "$config"

# Change variables in configuration
ynh_replace_string "__DBUSER__"    "$dbuser"   "$config"
ynh_replace_string "__DBPWD__"     "$dbpass"   "$config"
ynh_replace_string "__DBNAME__"    "$db_name"   "$config"
ynh_replace_string "__ADMINMAIL__" "$admin_mail" "$config"
ynh_replace_string "__LANGUAGE__"  "$language" "$config"
ynh_replace_string "__DOMAIN__"    "$domain"   "$config"
ynh_replace_string "__PATH__"      "$path_url" "$config"

#=================================================
# Replace logo image (default is FramaDate)
#=================================================

cp ../img/logo.png "$final_path/images"

#=================================================
# STORE THE CHECKSUM OF THE CONFIG FILE
#=================================================

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum "$config"

#=================================================
# Create log file
#=================================================

# Create log file
touch "$final_path/admin/stdout.log"


#=================================================
# GENERIC FINALIZATION
#=================================================
# Run database initilization
#=================================================

# Set initial permissions of initilization
chown -R "$app": "$final_path"

init_composer "$app" "$final_path"

sudo -u "$app" php "$final_path/admin/migration.php"

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

chown -R root: "$final_path"
chown -R "$app": "$final_path/tpl_c"
chown -R "$app": "$final_path/admin/stdout.log"

#=================================================
# SETUP SSOWAT
#=================================================

ynh_app_setting_set "$app" skipped_uris "/"

if [ $is_public -eq 0 ];
then
	ynh_app_setting_set "$app" protected_uris "/"
else
	ynh_app_setting_set "$app" protected_uris "/admin"
	ynh_replace_string "	include conf.d/"  "	#include conf.d/"  "$finalnginxconf"

	ynh_store_file_checksum "$finalnginxconf"
fi

#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx
