#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Configuring PHP-FPM..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.php" --destination="$install_dir/app/inc/config.php"

#=================================================
# REPLACE LOGO IMAGE (DEFAULT IS FRAMADATE)
#=================================================

cp ../sources/logo.png "$install_dir/images"

#=================================================
# Avoid PHPmailer issue
# https://github.com/YunoHost-Apps/opensondage_ynh/issues/95
#=================================================
if ! grep '^::1.*\s'"$main_domain" /etc/hosts > /dev/null
then
    sed -i '/^::1\s/s/$/ '"$main_domain"'/' /etc/hosts
fi

#=================================================
# CREATE LOG FILE
#=================================================

touch "$install_dir/admin/stdout.log"

#=================================================
# RUN DATABASE INITILIZATION
#=================================================
ynh_script_progression "Initializing database..."

ynh_composer_install
ynh_composer_exec install --no-dev

ynh_hide_warnings php$php_version "$install_dir/admin/migration.php"

chown -R $app: "$install_dir/"{tpl_c,admin/stdout.log}

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
