#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)

# Remove sources
ynh_secure_remove "/var/www/$app"

# Remove configuration files
ynh_secure_remove /etc/nginx/conf.d/$domain.d/$app.conf

ynh_secure_remove /etc/php5/fpm/pool.d/$app.conf
ynh_secure_remove /etc/php5/fpm/conf.d/20-$app.ini

# Drop MySQL database and user
dbname=$app
dbuser=$app
ynh_mysql_drop_db "$dbname" || true
ynh_mysql_drop_user "$dbuser" || true

service nginx reload
service php5-fpm reload
