#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
. /usr/share/yunohost/helpers

# Retrieve old app settings
domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" path)
admin=$(ynh_app_setting_get "$app" admin)
is_public=$(ynh_app_setting_get "$app" is_public)
public_site=$(ynh_app_setting_get "$app" public_site)
legal=$(ynh_app_setting_get "$app" legal)

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app \
    || ynh_die "Path not available: ${domain}${path}"


final_path=/var/www/$app
if [ -d $final_path ]; then
     ynh_die "There is already a directory: $final_path "
fi

conf=/etc/nginx/conf.d/$domain.d/$app.conf
if [ -f $conf ]; then
    ynh_die "There is already a nginx conf file at this path: $conf "
fi

phpconf=/etc/php5/fpm/pool.d/$app.conf
if [ -f $phpconf ]; then
    ynh_die "There is already a php-fpm conf file at this path: $phpconf "
fi

phpini=/etc/php5/fpm/conf.d/20-$app.ini
if [ -f $phpini ]; then
    ynh_die "There is already a php-fpm ini file at this path: $phpini "
fi

# Dependences
ynh_package_install php-fpdf

# Restore sources & data
sudo cp -a ./sources $final_path

dbname=$app
dbuser=$app
dbpass=$(ynh_app_setting_get "$app" mysqlpwd)
ynh_mysql_create_db "$dbname" "$dbuser" "$dbpass"
ynh_mysql_connect_as "$dbuser" "$dbpass" "$dbname" < ./dump.sql

# Set permissions
sudo chmod 700 $final_path/admin/logs_studs.txt
sudo chown -R www-data:www-data $final_path

# Restore conf files
sudo cp -a ./nginx.conf $conf
sudo cp -a ./php-fpm.conf $phpconf
sudo chown root: $phpconf
sudo chmod 644 $phpconf
sudo cp -a ./php-fpm.ini $phpini
sudo chown root: $phpini
sudo chmod 644 $phpini

# Set Administrator
if ynh_user_exists $admin; then
    sudo yunohost app addaccess $app -u $admin
fi

# Reload Nginx
sudo service php5-fpm restart
sudo service nginx reload

# Set ssowat config
ynh_app_setting_set "$app" skipped_uris "/"
if [[ $is_public -eq 0 ]];
then
	ynh_app_setting_set "$app" protected_uris "/admin,/index.php,/choix_date.php,/choix_autre.php,/infos_sondage.php,/scripts"
else
	ynh_app_setting_set "$app" protected_uris "/admin/index.php,/admin/logs_studs.txt,/scripts"
fi
sudo yunohost app ssowatconf
